export { Menu } from './Menu/Menu.lazy'
export { Cart } from './Cart/Cart.lazy'
export { Error } from './Error/Error.lazy'
export { Product } from './Product/Product.lazy'
export { Login } from './Login/Login.lazy'
export { Register } from './Register/Register.lazy'
